name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8550'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_open_v'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'kalama'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true
        default: 'android13'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '5.15'
      KERNEL_NAME:
        description: "自定义内核名称"
        required: true
        default: '-android13-8-o-01130-gdcaeece55887'
      KERNEL_VER:
        description: "自定义版本"
        required: true
        default: 'default'
      kernelsu_variant:
        description: "选择 KSU"
        required: true
        type: choice
        options:
          - KSU
          - KSUN
          - MKSU
          - RKSU
          - SKSU
        default: RKSU
      kernelsu_version:
        description: "选择 KSU 版本"
        required: true
        type: choice
        options:
          - tag[Releases]
          - main[Ci]
        default: main[Ci]
      SUSFS_ENABLED:
        description: "添加 SUSFS"
        required: true
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Configure Git
        run: |
         git config --global user.name "DogEZ"
         git config --global user.email "DdogezD@gmail.com"

      - name: Install dependencies
        run: |
         sudo apt update && sudo apt upgrade -y
         sudo apt install -y python3 git curl

      - name: Install repo tool
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
         mkdir kernel_workspace && cd kernel_workspace
         repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
         repo sync
         rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
         rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
         sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
         sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion

      - name: KSU & MKSU & RKSU Version
        run: |
         if [[ "${{ github.event.inputs.kernelsu_version }}" == "tag[Releases]" ]]; then
           echo "BRANCH=-" >> $GITHUB_ENV
         elif [[ "${{ github.event.inputs.kernelsu_version }}" == "main[Ci]" ]]; then
         if [[ "${{ github.event.inputs.kernelsu_variant }}" == "KSU" || "${{ github.event.inputs.kernelsu_variant }}" == "MKSU" || "${{ github.event.inputs.kernelsu_variant }}" == "RKSU" ]]; then
           echo "BRANCH=-s main" >> $GITHUB_ENV
          fi
         fi

      - name: Add KernelSU
        run: |
          cd kernel_workspace/kernel_platform
          if [ "${{ github.event.inputs.kernelsu_variant }}" == "KSU" ]; then
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash ${{ env.BRANCH }}
          elif [ "${{ github.event.inputs.kernelsu_variant }}" == "KSUN" ]; then
            curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash ${{ env.BRANCH }}
          elif [ "${{ github.event.inputs.kernelsu_variant }}" == "MKSU" ]; then
            curl -LSs "https://raw.githubusercontent.com/5ec1cff/KernelSU/main/kernel/setup.sh" | bash ${{ env.BRANCH }}
          elif [ "${{ github.event.inputs.kernelsu_variant }}" == "RKSU" ]; then
            curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
          elif [ "${{ github.event.inputs.kernelsu_variant }}" == "SKSU" ]; then
            curl -LSs "https://raw.githubusercontent.com/ShirkNeko/KernelSU/main/kernel/setup.sh" | bash -s susfs-dev
          fi
          
      - name: Add Configuration Settings
        if: github.event.inputs.SUSFS_ENABLED == 'true'
        run: |
          cd kernel_workspace/kernel_platform
          
          echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          
      - name: Handle KernelSU Version
        run: |
         if [[ "${{ github.event.inputs.kernelsu_variant }}" == "KSUN" ]]; then
            cd kernel_workspace/kernel_platform/KernelSU-Next
            MAKE_FILE="kernel/Makefile"
            DEFAULT_VERSION=11998
         else
            cd kernel_workspace/kernel_platform/KernelSU
            MAKE_FILE="kernel/Makefile"
            DEFAULT_VERSION=16    
         fi

         if [[ "${{ github.event.inputs.KERNEL_VER }}" == "default" ]]; then
            KSU_VERSION=$(( $(git rev-list --count HEAD) + 10200 ))
         else
            KSU_VERSION=${{ github.event.inputs.KERNEL_VER }}
         fi
    
         sed -i "s/DKSU_VERSION=${DEFAULT_VERSION}/DKSU_VERSION=${KSU_VERSION}/" "${MAKE_FILE}"
         echo "KSUVER=${KSU_VERSION}" >> $GITHUB_ENV

      - name: Add make name
        run: |
         export KBUILD_BUILD_TIMESTAMP=1744281706
         cd kernel_workspace/kernel_platform
         sed -i '$s|echo "\$res"|echo "\${{ github.event.inputs.KERNEL_NAME }}"|' ./common/scripts/setlocalversion
         sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
          
      - name: Build kernel
        run: |
         cd kernel_workspace
         LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ github.event.inputs.CPUD }} gki

      - name: Prepare Kernel
        run: |
         cp kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/dist/Image ./kernel_workspace/kernel

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
         name: Image-KernelSU_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
         path: kernel_workspace/kernel
